<?php

/**
 * @file
 * Install, update and uninstall functions for the vopros_embed module.
 */

/**
 * Remove color and logo configuration.
 */
function vopros_embed_update_7101() {
  variable_del('vopros_embed_logo');
  variable_del('vopros_embed_header_title_color');
  variable_del('vopros_embed_header_background_color');
  variable_del('vopros_embed_title');
  variable_del('vopros_embed_tab_title');
}
