<?php

include_once 'vopros_mailhandler.features.inc';

/**
 * Implements hook_init().
 */
function vopros_mailhandler_init() {
  if (user_access('access administration pages') &&
      !variable_get('vopros_mailhandler_configured', FALSE)) {
    $mailboxes = mailhandler_mailbox_load_all(FALSE);
    if (count($mailboxes) < 1) {
      drupal_set_message(t('No mailboxes configured for automatic mail import. Please <a href=@url>add a mailbox</a>.', array('@url' => 'admin/structure/mailhandler/add')), 'error');
    }
    else {
      variable_set('vopros_mailhandler_configured', TRUE);
    }
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function vopros_mailhandler_feeds_plugins() {
  return array(
    'VoprosMailhandlerParser' => array(
      'name' => 'Vopros mailhandler IMAP stream parser',
      'description' => 'Parses an IMAP stream.',
      'handler' => array(
        'parent' => 'MailhandlerParser',
        'class' => 'VoprosMailhandlerParser',
        'file' => 'VoprosMailhandlerParser.inc',
        'path' => drupal_get_path('module', 'vopros_mailhandler') . '/plugins/mailhandler',
      ),
    ),
    'VoprosMailhandlerProcessor' => array(
      'name' => 'Vopros email processor',
      'description' => 'Create Email entities and update question status.',
      'help' => '',
      'handler' => array(
        'parent' => 'FeedsProcessor',
        'class' => 'VoprosMailhandlerProcessor',
        'file' => 'VoprosMailhandlerProcessor.inc',
        'path' => drupal_get_path('module', 'vopros_mailhandler') . '/plugins/mailhandler',
      ),
    ),
  );
}
