<?php

include_once 'vopros_mailhandler.features.inc';

/**
 * Implements hook_init().
 */
function vopros_mailhandler_init() {
  // Try to skip ajax calls.
  // Using drupal_installation_attempted() to defer warnings until the
  // installation is complete.
  if (strpos(current_path(), 'ajax') === FALSE &&
    !drupal_installation_attempted() &&
      user_access('access administration pages') &&
      !variable_get('vopros_mailhandler_configured', FALSE)) {
    $mailboxes = mailhandler_mailbox_load_all(FALSE);
    if (count($mailboxes) < 1) {
      drupal_set_message(t('No mailboxes configured for automatic mail import. Please <a href=@url>add a mailbox</a>.', array('@url' => 'admin/structure/mailhandler/add')), 'error', FALSE);
    }
    else {
      variable_set('vopros_mailhandler_configured', TRUE);
    }
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function vopros_mailhandler_feeds_plugins() {
  return array(
    'VoprosMailhandlerParser' => array(
      'name' => 'Vopros mailhandler IMAP stream parser',
      'description' => 'Parses an IMAP stream.',
      'handler' => array(
        'parent' => 'MailhandlerParser',
        'class' => 'VoprosMailhandlerParser',
        'file' => 'VoprosMailhandlerParser.inc',
        'path' => drupal_get_path('module', 'vopros_mailhandler') . '/plugins/mailhandler',
      ),
    ),
    'VoprosMailhandlerProcessor' => array(
      'name' => 'Vopros email processor',
      'description' => 'Create Email entities and update question status.',
      'help' => '',
      'handler' => array(
        'parent' => 'FeedsProcessor',
        'class' => 'VoprosMailhandlerProcessor',
        'file' => 'VoprosMailhandlerProcessor.inc',
        'path' => drupal_get_path('module', 'vopros_mailhandler') . '/plugins/mailhandler',
      ),
    ),
  );
}

/**
 * Implements hook_vopros_extra_permissions().
 */
function vopros_mailhandler_vopros_extra_permissions() {
  return array(
    'staff' => array('administer mailhandler'),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add submit handler to filter out mailhandlers verbose messages when saving
 * mailbox. They're irrelevant/misleading in our setup.
 */
function vopros_mailhandler_form_ctools_export_ui_edit_item_form_alter(&$form, $form_state, $form_id) {
  // Damn you ctools for not making it more obvious.
  if (isset($form_state['plugin']['name']) &&
    isset($form_state['plugin']['module']) &&
    $form_state['plugin']['name'] == 'mailhandler' &&
    $form_state['plugin']['module'] == 'mailhandler'
  ) {
    $form['#submit'][] = 'vopros_mailhandler_mailbox_submit';
  }
}

/**
 * Submit handler to filter out verbose mailhandler messages.
 */
function vopros_mailhandler_mailbox_submit() {
  $prefix = "Now that you've created a mailbox";
  $messages = drupal_get_messages('status');
  foreach ($messages['status'] as $message) {
    if (substr($message, 0, strlen($prefix)) != $prefix) {
      drupal_set_message($message, 'status', TRUE);
    }
  }
}
